"""Build the Word Guess word list.

Downloads a comprehensive English word list and a curated common-words list,
filters to 5-letter lowercase a-z, and writes them as a JS file consumed by
the game. The "answers" list is used to pick today's puzzle; the "valid"
list is the broader set of words a player may guess.

Run: python tools/build_word_list.py
"""

import os
import re
import sys
import urllib.request

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "static", "games", "word-guess", "words.js",
)

# dwyl/english-words — large MIT-licensed alpha-only English word list.
ALL_URL = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"

# google-10000-english — most common English words, used to pick familiar
# answers so the daily puzzle isn't full of obscure terms.
COMMON_URL = (
    "https://raw.githubusercontent.com/first20hours/google-10000-english/"
    "master/google-10000-english-no-swears.txt"
)


def fetch(url):
    print(f"Fetching {url}", file=sys.stderr)
    req = urllib.request.Request(url, headers={"User-Agent": "game-galaxy-build/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def five_letter_words(text):
    out = []
    seen = set()
    for raw in text.splitlines():
        w = raw.strip().lower()
        if len(w) == 5 and re.fullmatch(r"[a-z]{5}", w) and w not in seen:
            seen.add(w)
            out.append(w)
    return out


def main():
    valid = five_letter_words(fetch(ALL_URL))
    common = five_letter_words(fetch(COMMON_URL))

    # Answers: common 5-letter words that are also in the broad valid list.
    valid_set = set(valid)
    answers = [w for w in common if w in valid_set]
    answers_set = set(answers)

    # Make sure every answer is also a valid guess.
    valid_full = sorted(valid_set | answers_set)

    print(
        f"Valid guesses: {len(valid_full)}; answers: {len(answers)}",
        file=sys.stderr,
    )

    lines = []
    lines.append("// Auto-generated by tools/build_word_list.py — do not edit by hand.")
    lines.append(f"// Sources: {ALL_URL}")
    lines.append(f"//          {COMMON_URL}")
    lines.append(f"// {len(valid_full)} valid guesses, {len(answers)} daily-puzzle answers.")
    lines.append("window.GG_ANSWERS = [")
    for i in range(0, len(answers), 12):
        chunk = ",".join(f'"{w}"' for w in answers[i:i + 12])
        lines.append("  " + chunk + ",")
    lines.append("];")
    lines.append("window.GG_VALID = [")
    for i in range(0, len(valid_full), 12):
        chunk = ",".join(f'"{w}"' for w in valid_full[i:i + 12])
        lines.append("  " + chunk + ",")
    lines.append("];")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
